name: flutter_find_places
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_google_places: ^0.3.0
  geolocator: ^9.0.2
  get: 4.6.5
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.5
  http: ^0.13.4
  path_provider: ^2.0.14
  sembast: any
  sembast_web: any
  smooth_star_rating_null_safety: ^1.0.4+2
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
